### ISSUE TITLE
Loading or saving config file doesn't works.

### ISSUE THREAD

**Issue by gaeulbyul** [Genivia/ugrep#100]
Envrionment
=====

- Windows 10 [Version 10.0.19042.746]
- ugrep: ugrep 3.1.4 WIN64 +avx2 +pcre2_jit +zlib +bzip2 +lzma +lz4 ( Downloaded from https://github.com/Genivia/ugrep/releases/tag/v3.1.4 )

Bug 1
=====

ugrep doesn't create config file if not exist.

Steps to reproduce:
-----

1. Ensure ".ugrep" file doesn't exist on home directory.
2. Run `ugrep --save-config`, or `ugrep --ignore-files --save-config`
3. Check home directory

Expected result:
-----

Config file(".ugrep") generated on home directory

Actual result:
-----

ugrep shows error message ("ugrep: cannot save configuration file .ugrep") and there's no config file

* * *

Bug 2
=====

When I create ".ugrep" file manually, ugrep still doesn't write config file. (without error message)

Steps to reproduce:
-----

1. Create ".ugrep" file into home directory.
2. Run `ugrep --save-config`, or `ugrep --ignore-files --save-config`
3. Check ".ugrep" file.

Expected result:
-----

".ugrep" file modified with new configuration

Actual result:
-----

".ugrep" file still remains as is. ugrep doesn't shows error message at this time.

* * *

Bug 3
=====

Loading config file also doesn't work unless giving `--config=.ugrep` option explicitly.

Steps to reproduce:
-----

1. Ensure ".ugrep" config file exists. (with some configurataion)
2. Run `ug`
3. check those config applied correctly.

Expected Result:
-----

ugrep runs as some configurations.

Actual result:
-----

ugrep runs like there's no config file.

**Comment by genivia-inc** [comment]
Thanks for reporting this issue and sorry for the trouble. Fixed in v3.1.5.

**Comment by gaeulbyul** [comment]
Hello. Looks like bug-3(loading .ugrep file doesn't work) is still not fixed yet. Would you mind checking it again?

**Comment by genivia-inc** [comment]
My win64 version of ugrep v3.1.6 works fine, e.g. `ugrep --config ...`. This loads `.ugrep`. Also `ug.exe ...` works as expected.

**Comment by gaeulbyul** [comment]
Oh, never mind. `ug.exe ...` loads config file well.
