### ISSUE TITLE
ugrepping /sys/kernel takes too long or grepping /sys/kernel is not thorough

### ISSUE THREAD

**Issue by PeterMuellerr** [Genivia/ugrep#193]
Following up on [Ricardo's request](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006978#10):
Searching for a string in `/sys/kernel` on Debian stable with `grep` terminates within 3 seconds (and spits out many error messages, which is expected).  Searching for the same string with `ugrep` (and avoiding following the soft links) doesn't terminate over half an hour and spits out no error messages. Therefore, `ugrep` has a deficiency somewhere (or grep doesn't do its job thoroughly).

```
# time -p grep -i -r dvistyle /sys/kernel
… (error messages)…
real 2,75
user 0,05
sys 1,06
# date && time -p ugrep -i -r -p dvistyle /sys/kernel
Mi 9. Mär 20:34:45 CET 2022
^Creal 2162,92
user 0,04
sys 0,28
# date
Mi 9. Mär 21:10:49 CET 2022
#

```

**Comment by genivia-inc** [comment]
The user and sys times of ugrep show low values, so it is not clear to me what's happening here. Try searching with one thread with option `-J1`. I'm curious if this is caused by some (thread) resource contention.

**Comment by PeterMuellerr** [comment]
> The user and sys times of ugrep show low values, so it is not clear to me what's happening here. Try searching with one thread with option `-J1`. I'm curious if this is caused by some (thread) resource contention.

I don't know why user and sys are low. In any case, `ugrep` ran about 35 minutes long. I'll report about -J1 here in short.

**Comment by genivia-inc** [comment]
Ugrep works fine to search `ugrep -i -r -p dvistyle /sys/kernel` on the RPi I use for testing ugrep with Linux+ARM. It completes the search in 0.05s on a slow RPi.

But Linux distros differ. As we all know, files in the /proc filesystem aren't really files. Searching some of these may cause issues. Perhaps some of these "files" may never return EOF to produce a stream of data like PRNG urandom "files" do.

Why bother searching /proc?

**Comment by genivia-inc** [comment]
I've also tested this with a Ubuntu Docker container. No issues with searching /sys/kernel either.

**Comment by PeterMuellerr** [comment]
Concerning “why bother searching /proc and /sys”: you do it implicitly while searching everywhere. Originally, I issued the command `ugrep -i -r -z -p dvistyle / 2>>/dev/null` (to check whether a file with a particular contents exists at all), found out that the search took too long, aborted it, and while debugging I determined that searching `/sys` is the culprit.

**Comment by genivia-inc** [comment]
Well, /sys/kernel/security/apparmor/revision is a regular file, not a device, right? Ugrep does not read named pipes and named sockets by default, because we don't want to forever hang on those. Ugrep only reads regular files and skips named pipes and named sockets unless `-Dread` is used:
~~~
mkfifo pipe1
grep -c '' pipe1   # hangs
grep -c '' *   # hangs
grep -c ''   # does not hang
grep -r -c '' -Dread   # hangs
ugrep -c -r ''   # does not hang
ugrep -c -r '' -Dread   # hangs
~~~
There are plenty of posts about such issues with named pipes and sockets, see for example https://serverfault.com/questions/439705/recursive-grep-started-at-hangs and https://unix.stackexchange.com/questions/499229/grep-exclude-option-doesnt-always-skip-named-pipes and https://unix.stackexchange.com/questions/7086/grep-acting-strangely

I don't understand why searching /sys/kernel/security/apparmor/revision hangs _when it is a regular file_. Hanging can only happen If there is no EOF at all, like what happens with named pipes, but not with regular files.

Since grep reports "Resource temporarily unavailable", it uses a non-blocking read operation. However, what if the resource becomes available? In most cases we want to keep searching. The approach to immediately give up on EAGAIN may or may not be desirable from the user's perspective. This is something to think about perhaps, before proposing a "fix". There has to be a compelling reason to choose to abort instead of waiting until the resource becomes available to read.

**Comment by PeterMuellerr** [comment]
@genivia-inc I have no idea whether /sys/kernel/security/apparmor/revision is a _regular_ file; size 0 and contents "12" (see above) suggest there is something special about it. (By the way, on another Debian computer, I get size 0 and contents "10" instead of "12".)
As for the compelling reason, my original goal was to search for a particular string (here, `dvistyle`) on the whole file system, including the compressed files (that's why I use `ugrep` instead of `grep`). I guess, this is a valid reason, isn't it? So, if this can be implemented in one or another way, with some additional switches or by default, I'd be happy.
By the way, here is what grep does:
```
 # grep -r dvistyle /sys/kernel/security/apparmor
grep: /sys/kernel/security/apparmor/revision: Resource temporarily unavailable
grep: /sys/kernel/security/apparmor/.remove: Invalid argument
grep: /sys/kernel/security/apparmor/.replace: Invalid argument
grep: /sys/kernel/security/apparmor/.load: Invalid argument
# grep dvistyle /sys/kernel/security/apparmor/revision
^C # hangs, interruped via Ctrl+C.
```

**Comment by genivia-inc** [comment]
Thanks for sharing the details. I know it's frustrating that this search won't make any progress.

Others have asked my for options to exclude non-regular file systems from the search. To do so, I added the `--include-fs` and `--exclude-fs` options. Use `--exclude-fs=/sys,/proc` to skip /sys and /proc file systems entirely and skip anything linked to those fs. Or use `--include-fs=/` to search only non-mounted fs on root. This also skips any thumb drives and other mounted fs:
~~~
    --include-fs=MOUNTS
            Only file systems specified by MOUNTS are included in recursive
            searches.  MOUNTS is a comma-separated list of mount points or
            pathnames of directories on file systems.  --include-fs=. restricts
            recursive searches to the file system of the working directory
            only.  Note that --exclude-fs mounts take priority over
            --include-fs mounts.  This option may be repeated.
~~~
I'm still curious what /sys/kernel/security/apparmor/revision really is and why the OS reports this as a `DIRENT_TYPE_REG` and `S_ISREG` (regular file). I will take a closer look when I have time.

**Comment by PeterMuellerr** [comment]
> Others have asked my for options to exclude non-regular file systems from the search. To do so, I added the `--include-fs` and `--exclude-fs` options. Use `--exclude-fs=/sys,/proc` to skip /sys and /proc file systems entirely and skip anything linked to those fs. Or use `--include-fs=/` to search only non-mounted fs on root. This also skips any thumb drives and other mounted fs:
> 
> ```
>     --include-fs=MOUNTS
>             Only file systems specified by MOUNTS are included in recursive
>             searches.  MOUNTS is a comma-separated list of mount points or
>             pathnames of directories on file systems.  --include-fs=. restricts
>             recursive searches to the file system of the working directory
>             only.  Note that --exclude-fs mounts take priority over
>             --include-fs mounts.  This option may be repeated.
> ```
> 
> I'm still curious what /sys/kernel/security/apparmor/revision really is and why the OS reports this as a `DIRENT_TYPE_REG` and `S_ISREG` (regular file). I will take a closer look when I have time.

Thanks! Well, I ended up searching each subdirectory of / separately except /proc and /sys. This is, I guess, equivalent to `--exclude-fs=/sys,/proc`.  Doing `--include-fs=/` would skip /boot and /home when they are on separate partitions, wouldn't it?
In any case, /sys also contains normal regular files, say, /sys/kernel/boot_params/version, which might be worth searching. While in my particular case `dvistyle` is not expected there (if it were, I would be very surprised), in general skipping /sys and /proc entirely might lead to genuinely missed contents.
As for /sys/kernel/security/apparmor/revision, it's just an example. There are other directories or files on which ugrep makes no progress (say, /sys/kernel/debug/). However, let's tackle them one by one.

**Comment by genivia-inc** [comment]
I believe I may have a solution, but this needs verification and testing.

The /sys/kernel/security/apparmor/revision file is a regular file, so the current ugrep logic does not suffice to skip this file.

So I found a similar problem with Ubuntu /proc/self/pagemap that is a regular file, but `fread()` on this file always returns data (zeros) of the max length specified. However, a non-buffered `read()` on this file fails with "Invalid argument" (errno=EINVAL). Therefore, we should be able to use `read()` to detect these "regular files" that are not actually searchable.

The following patch works with Ubuntu for me, with the logic in the new `#ifndef OS_WIN...#endif` block:

ugrep.cpp:2945 in function `open_file()`:
~~~
    else if (fopenw_s(&file_in, pathname, "rb") != 0)
    {
      warning("cannot read", pathname);

      return false;
    }

#ifndef OS_WIN
    // check if the regular file is readable
    struct stat buf;
    if (fstat(fileno(file_in), &buf) == 0 && S_ISREG(buf.st_mode))
    {
      char data[1];
      if (read(fileno(file_in), data, 1) < 0 || fseek(file_in, 0, SEEK_SET) != 0)
      {
        warning("cannot read", pathname);
        fclose(file_in);

        return false;
      }
    }
#endif
~~~
Because the `read()` fails (which I verified), this gives:
~~~
ugrep -l '' /proc/self/pagemap 
ugrep: warning: cannot read /proc/self/pagemap: Invalid argument
~~~
The "Invalid argument" looks a bit odd though.

Funny that GNU grep 3.1 gives no error at all:
~~~
grep -l '' /proc/self/pagemap   # OK, no error or hanging
~~~
but hangs with option `-c`:
~~~
grep -c '' /proc/self/pagemap   # hangs
~~~
So there are different behaviors.

I tried with non-blocking file FD to see if the attempted read produces a "Resource temporarily unavailable" (errno=EAGAIN) but no, that does not happen, still getting EINVAL. Actually setting regular file FD to non-blocking is not useful.

**Comment by PeterMuellerr** [comment]
@genivia-inc Thanks for digging into it! I'm afraid I cannot comment on you code except that `if (fstat(fileno(file_in), &buf) == 0 && S_ISREG(buf.st_mode))` could probably be written shorter as `if( !fstat(fileno(file_in), &buf) && S_ISREG(buf.st_mode))` and `if (read(fileno(file_in), data, 1) < 0 || fseek(file_in, 0, SEEK_SET) != 0)` could probably be written shorter as `if (read(fileno(file_in), data, 1) < 0 || fseek(file_in, 0, SEEK_SET))`, unless my C-language knowledge is outdated. Still, if you think you have something that can be tested, feel free to say so so that the maintainer can package it and put into Debian experimental.

**Comment by genivia-inc** [comment]
Another simpler approach is to skip empty files, just don't search them. Both GNU grep and BSD grep skip empty files in recursive searches, except for GNU grep option -c. Don't ask why GNU grep -c is an exception. If we skip regular files that are empty, then this problem with all sysfs files in /proc and /sys goes away.
~~~
#ifndef OS_WIN
    // skip empty regular files
    struct stat buf;
    if (fstat(fileno(file_in), &buf) == 0 && S_ISREG(buf.st_mode) && buf.st_size == 0)
    {
      fclose(file_in);
      file_in = NULL;

      return false;
    }
#endif
~~~
But ugrep -c will no longer report a 0 for empty files. I don't know if that is an issue. Perhaps we need to add a special case for option -c to emulate GNU grep.

**Comment by genivia-inc** [comment]
This change is really tiny, so I don't expect this to break anything. I've verified the approach. This works on Ubuntu, Debian-based RPi, Android with termux, Cygwin and I also checked if all is OK on non-Linux OS such as Windows and MacOS.

**Comment by genivia-inc** [comment]
Fixed in v3.7.5.

**Comment by PeterMuellerr** [comment]
Very many thanks! I've just pinged the maintainer to push the fix into Debian experimental.

**Comment by PeterMuellerr** [comment]
Unfortunately, the bug still exists in 3.7.5:
```
# ugrep --version
ugrep 3.7.5 x86_64-pc-linux-gnu +sse2 +pcre2_jit +zlib +bzip2 +lzma +lz4 +zstd
License BSD-3-Clause: <https://opensource.org/licenses/BSD-3-Clause>
Written by Robert van Engelen and others: <https://github.com/Genivia/ugrep>
# time -p ugrep -i -r -p dvistyle /sys/kernel
ugrep: warning: cannot read /sys/kernel/tracing/saved_cmdlines_size: Resource temporarily unavailable
ugrep: warning: cannot read /sys/kernel/tracing/trace_marker: Resource temporarily unavailable
ugrep: warning: cannot read /sys/kernel/tracing/free_buffer: Resource temporarily unavailable
ugrep: warning: cannot read /sys/kernel/tracing/trace_marker_raw: Resource temporarily unavailable
ugrep: warning: cannot read /sys/kernel/tracing/tracing_cpumask: Resource temporarily unavailable
^C
real 150,22
user 0,02
sys 0,21
# time -p ugrep -i -r -p dvistyle /sys/kernel/security/apparmor
^C
real 156,94
user 0,00
sys 0,00
# time -p ugrep -i -p dvistyle /sys/kernel/security/apparmor/revision
^C
real 100,52
user 0,00
sys 0,00
# ls -laF /sys/kernel/security/apparmor/revision
-r--r--r-- 1 root root 0 Mar 17 12:24 /sys/kernel/security/apparmor/revision
# cat /sys/kernel/security/apparmor/revision
12
^C
# getfacl /sys/kernel/security/apparmor/revision
getfacl: Removing leading '/' from absolute path names
# file: sys/kernel/security/apparmor/revision
# owner: root
# group: root
user::r--
group::r--
other::r--

# getfattr -d -m - /sys/kernel/security/apparmor/revision
#
```
The entries ^C result from my interruption with Ctrl+C. I nudged the Debian maintainer again so that he provides you with the details on the file /sys/kernel/security/apparmor/revision file; no answer so far. The architecture is amd64; the used distribution is Debian stable “bullseye” with minor updates.

**Comment by PeterMuellerr** [comment]
@genivia-inc … and please reopen the issue …

**Comment by genivia-inc** [comment]
The update works as long as the `fstat` of a sysfd file returns a file size of 0 (like `ls` reports file size 0) and syscall `read()` fails. This is a safe check. Otherwise, I don't think we can guarantee not to accidentally omit files that should actually be searchable, which would be bad. Anyhow, on the various systems I've tested this check suffices to skip such sysfd files without accidentally skipping regular files that should be searched.

Note that a direct GNU grep on such a sysfd file hangs too, but GNU grep may use a different check for skipping such files when recursing. But what GNU grep uses is not clear to me.

Not reopening until someone has a better patch or better suggestion.

**Comment by PeterMuellerr** [comment]
@genivia-inc Are you saying the Linux file system on Debian (or partiuclar files) are too screwed to be search recursively thoroughly? If so, we'd better file a bug report against it. 
Still, pragmatically, recursive search in / is clearly desirable. To this end, you might simply consider introducing a command-line switch, say, „--skip_empty“, which skips all files of size 0 (regardless of whether a read would succeed or fail on them). At least that's what the user can tell about the file /sys/kernel/security/apparmor/revision using command-line tools.

**Comment by ribalda** [comment]
Seems like the revision file is perhaps too creative :) https://gitlab.com/apparmor/apparmor/-/wikis/AppArmorInterfaces#syskernelsecurityapparmorrevision

I believe that it does not affect grep, because it opens files with `O_NONBLOCK` when working in recursive mode:

```
$ strace -f  grep -r  dvistyle /sys/kernel/security/apparmor
....
openat(4, "revision", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_NOFOLLOW) = 3
...
$ strace -f  grep   dvistyle /sys/kernel/security/apparmor/revision
...
openat(AT_FDCWD, "/sys/kernel/security/apparmor/revision", O_RDONLY|O_NOCTTY)
...
```
Maybe ugrep could take a similar approach.

**Comment by genivia-inc** [comment]
@ribalda good point to look at GNU grep's logic. The non-blocking open in GNU grep was my guess, given the EAGAIN error message by GNU grep.

Perhaps the following change to the `open_file()` code is best to handle all such cases for such "regular files":
~~~
#ifndef OS_WIN
    struct stat buf;
    if (fstat(fileno(file_in), &buf) == 0 && S_ISREG(buf.st_mode))
      fcntl(fileno(file_in), F_SETFL, fcntl(0, F_GETFL) | O_NONBLOCK);
#endif
~~~
Note that the change will not distinguish recursively found files and files specified on the command line. Both will be set to non-blocking. I don't see the point of GNU grep distinguishing these two cases, recursive vs. files on the command line. Does that make sense?

In addition, some more logic is needed to produce the EAGAIN warning/error message. Or should we silently stop reading these "files" without producing warnings?

BTW. In ugrep "interactive" mode, when a tty or a pipe is read from stdin, ugrep sets the fd to non-blocking which makes sense for these devices because ugrep will be able to flush results rather than waiting for a full buffer of input. It's something I thought would be best in that case as we can distinguish character devices and pipes.

**Comment by genivia-inc** [comment]
Alternatively, and this is a minor point, a hybrid approach can be more effective. We immediately skip "regular files" with zero size that aren't readable with `read()`, which we did in the previous patch that works very well to skip sysfd /proc and /sys files in all cases except the apparmor files and perhaps other cases. In addition, when the file size>0 or when readable, we set the fd to nonblocking (see my previous comment):
~~~
#ifndef OS_WIN
    // check if regular files are not readable, if readable enable non-blocking
    struct stat buf;
    if (fstat(fileno(file_in), &buf) == 0 && S_ISREG(buf.st_mode))
    {
      char data[1];
      if (buf.st_size == 0 && (read(fileno(file_in), data, 1) < 0 || fseek(file_in, 0, SEEK_SET) != 0))
      {
        errno = EAGAIN; // override the confusing "Invalid argument" (22) and "Input/output error" (5) ...
        warning("cannot read", pathname);
        fclose(file_in);
        file_in = NULL;

        return false;
      }

      fcntl(fileno(file_in), F_SETFL, fcntl(0, F_GETFL) | O_NONBLOCK);
    }
#endif
~~~

**Comment by ribalda** [comment]
Please note that there are regular valid files like eeproms, nvmems that might require a long time to be read and can only be read in page sizes. We cannot grep those files in `O_NONBLOCK` mode.

I think the safest approach is the one taken by gnu grep. blocking mode by file, non_block for recursive. I have no idea how difficult it is implement that in ugrep.

If that is not possible, I would say that I prefer a exclusive blocking mode, a grep over / is generally bad practice. And not allowing grep over a block device is killing a valid use-case.

**Comment by genivia-inc** [comment]
grep 3.3 appears to work differently though. It sets `O_NONBLOCK` when skipping devices (`-Dskip`), otherwise its blocking. It seems GNU grep versions have progressed/regressed on these issues the last few years?

So OK then, to only `O_NONBLOCK` when the recursion options are used (`-r`, `-R`, `--depth`, and ugrep default recursive search):
~~~
#ifndef OS_WIN
    // when opening a regular file, set fd to nonblocking and check if an empty file is readable e.g. not a sysfd file like in /proc and /sys
    struct stat buf;
    if (fstat(fileno(file_in), &buf) == 0 && S_ISREG(buf.st_mode))
    {
      // recursive searches should not block
      if (flag_directories_action == Action::RECURSE)
        fcntl(fileno(file_in), F_SETFL, fcntl(0, F_GETFL) | O_NONBLOCK);

      char data[1];
      if (buf.st_size == 0 && (read(fileno(file_in), data, 1) < 0 || fseek(file_in, 0, SEEK_SET) != 0))
      {
        warning("cannot read", pathname);
        fclose(file_in);
        file_in = NULL;

        return false;
      }
    }
#endif
~~~
This still skips empty files right away that are easily detectable as useless to search e.g. in /proc, whether specified on the command line or recursively.

**Comment by genivia-inc** [comment]
I will release an update soon that incorporates the suggested improvements and some additional features. (Sorry for the delay, I was out of town.)

**Comment by genivia-inc** [comment]
Version 3.7.7 is released.

I spent time testing the approach we discussed on various systems with success. I don't have a machine with /sys/kernel/security/apparmor so I could not 100% verify that the recursive search problem is gone with /sys/kernel/security/apparmor, but I am hopeful. The file open/read is nonblocking for recursive searches to prevent recursive searches from blocking. Non-recursive searches may still block. However, I've kept the quick-and-dirty empty file test with `read()` that fails to avoid those special sysfd files. This should be safe to skip these files (the file is empty anyway) and generally prevents blocking on those files.
