### ISSUE TITLE
Unable to build on Cygwin

### ISSUE THREAD

**Issue by ISO8807** [Genivia/ugrep#8]
I tried building ugrep 1.5.4 on Windows 10 using Cygwin's gcc. That would be handy, e.g. for symlinks. The build hits problems with fseeko and ftello:

  input.cpp:642:13: error: 'ftello' was not declared in this scope
  input.cpp:642:13: note: suggested alternative: 'ftell'

  input.cpp:737:2: error: 'fseeko' was not declared in this scope
  input.cpp:737:2: note: suggested alternative: 'fseek'

If I work around this, I then hit other problems with _vsnprintf, fopen_s and strerror_s:

  In file included from ugrep.cpp:104:0:
  /usr/include/w32api/strsafe.h:1555:12: error: '_vsnprintf' was not declared in this scope
  /usr/include/w32api/strsafe.h:1555:12: note: suggested alternative: 'vsnprintf'

  ugrep.cpp:1609:9: error: 'fopen_s' was not declared in this scope
  ugrep.cpp:1609:9: note: suggested alternative: '_fopen_r'

  ugrep.cpp:5370:5: error: 'strerror_s' was not declared in this scope
  ugrep.cpp:5370:5: note: suggested alternative: '_strerror_r'

Any chance of making this compile under Cygwin? Many thanks!

**Comment by genivia-inc** [comment]
To compile on Cygwin, c++ compiler option `-std=gnu++11` will be required. The current autoconf settings use `-std=c++11`. I'll see if there is a way to force this to use the GNU extensions.

**Comment by genivia-inc** [comment]
I've build ugrep v1.5.5 on Cygwin by changing `./configure.ac` to require GNU extensions. Should be fixed now.

**Comment by ISO8807** [comment]
Many thanks for the quick response. I tried building ugrep 1.5.5 under Cygwin. This now compiles input.cpp without errors, but compiling ugrep.cpp still fails on _vsnprintf, fopen_s and strerror_s (which probably don't exist on Cygwin). The build is now using "-std=gnu++11".

  make[2]: Entering directory 'ugrep-1.5.5/src'

  g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I..  -I../include  -DPLATFORM=\"i686-pc-cygwin\" -DGREP_PATH=\"/usr/local/share/ugrep/patterns\"  -Wall -Wunused -Wextra -g -O2 -MT ugrep-ugrep.o -MD -MP -MF .deps/ugrep-ugrep.Tpo -c -o ugrep-ugrep.o `test -f 'ugrep.cpp' || echo './'`ugrep.cpp
  
  In file included from ugrep.cpp:104:0:
  /usr/include/w32api/strsafe.h:1555:12: error: '_vsnprintf' was not declared in this scope
  /usr/include/w32api/strsafe.h:1555:12: note: suggested alternative: 'vsnprintf'

  ugrep.cpp:1609:9: error: 'fopen_s' was not declared in this scope
  ugrep.cpp:1609:9: note: suggested alternative: '_fopen_r'

  ugrep.cpp:5370:5: error: 'strerror_s' was not declared in this scope
  ugrep.cpp:5370:5: note: suggested alternative: '_strerror_r'
  
I don't know if the right #ifdefs would help here. Because __CYGWIN__ is predefined, OS_WIN is also being defined.

**Comment by ISO8807** [comment]
I changed ugrep.cpp at various points to say things like the following:

  #if defined(OS_WIN) && !defined(__CYGWIN__)

I can then build ugrep cleanly. This works fine with many files on the command line, so the other issue I had must be a limitation on the command line length for Windows native binaries.

**Comment by genivia-inc** [comment]
Thanks for the feedback. To prevent this from happening again, in `ugrep.cpp` I changed lines 92-94 as follows:
~~~
#if (defined(__WIN32__) || defined(_WIN32) || defined(WIN32) || defined(__BORLANDC__)) && !defined(__CYGWIN__) && !defined(__MINGW32__) && !defined(__MINGW64__)
# define OS_WIN
#endif
~~~
This update will be included in upcoming releases.

**Comment by ISO8807** [comment]
In case it helps, my edits to ugrep.cpp were as follows (line numbers are approximate):

// Around line 96
#if defined(OS_WIN) && !defined(__CYGWIN__)
#include <strsafe.h>
#endif

// Around line 464
#if !defined(OS_WIN) || defined(__CYGWIN__)

// Around line 5417
#if defined(__STDC_LIB_EXT1__) || (defined(OS_WIN) && !defined(__CYGWIN__))

// Around line 5436
#if defined(__STDC_LIB_EXT1__) || (defined(OS_WIN) && !defined(__CYGWIN__))
